TITLE CALCULADORA AVANÇADA

.MODEL SMALL

.DATA
    MSG1 db  10, 13, 'Digite o 1o numero: ','$'
    MSG2 db  10, 13, 'Digite o 2o numero: ','$'
    MSG3 db  10, 13, 'RESULTADO: ','$'
    PULA_LINHA db 10, 13, '$'
    
    NUM1 DB ?
    NUM2 DB ?
    RESULTADO DB ?

.CODE
MAIN PROC
    MOV AX,@DATA        
    MOV DS,AX           ;ININICIALIZA O DATA
    MOV ES,AX

    LEA DX, MSG1
    MOV AH, 09H         ; PRINT O MSG1 NA TELA
    INT 21H

    MOV AH,01H
    INT 21H             ; FAZ A ENTRADA DO PRIMEIRO NÚMERO
    SUB AL,30H          ; PASSA O CARACTER PARA NUMERO
    MOV NUM1, AL        ; ARMAZENA O NUMERO EM "NUM1"

    LEA DX, MSG2
    MOV AH, 09H         ; PRINT O MSG2 NA TELA
    INT 21H

    MOV AH,01H
    INT 21H             ; FAZ A ENTRADA DO SEGUNDO NÚMERO
    SUB AL,30H          ; PASSA O CARACTER PARA NUMERO
    MOV NUM2, AL        ; ARMAZENA O NUMERO EM "NUM2"

    MOV DL, NUM1        
    ADD DL, NUM2        ; FAZ A SOMA DOS NUMERO E ARMAZENA EM "RESULTADO"
    MOV RESULTADO, DL

    LEA DX, MSG3
    MOV AH, 09H         ; PRINT O MSG3 NA TELA
    INT 21H

    CALL OUTPUT         ; CHAMA A FUNÇÃO "OUTPUT"

    MOV AH, 4CH         ; ENCERRA O PROGRAMA!
    INT 21H

MAIN ENDP

OUTPUT PROC
    xor ax, ax          ;ZERA O CONTEÚDO DE AX
    MOV AL, RESULTADO   ;PASSA O RESULTADO PRA AL
    MOV BL, 10          ;ATRIBUI 10 PRA BL
    DIV BL              ;DIVIDI O AL POR 10 - (AL)/10 - AGORA O RESULTADO DA DIVISÃO ESTÁ EM AL
                        ; E O RESTO DA DIVISÃO ESTÁ EM AH
    MOV BX,AX           ;PASSA ESSE RESULTADOS PARA BX

    MOV DL, BL          
    ADD DL, 30H         ;IMPRIME O QUE ESTÁVA EM AL ANTERIORMENTE 
    MOV AH, 02H
    INT 21H
    
    MOV DL, BH
    ADD DL, 30H         ;IMPRIME O QUE ESTÁVA EM AH ANTERIORMENTE 
    MOV AH, 02H
    INT 21H

    RET                 ;RETORNA DA FUNÇÃO

OUTPUT ENDP

; OBS: SE VOCÊ TEM UM NÚMERO MAIOR DO QUE NOVE, ELE É DE VÁRIOS ALGARISMOS, EX: 1547 = 1000 + 500 + 40 + 7. 
; BASTA DIVIDIR POR 1000, DEPOIS POR 100, POR 10 E IR IMPRIMINDO O RESULTADO DA DIVISÃO E ARMAZENADO O RESTO QUE FALTA 
; 1547 / 1000 = 1 (PRINTAR ESSE 1) E 1547 % 1000 = 547 (ARMAZENE ESTA VALOR)
; 547 / 100 = 5 (PRINTAR ESSE 5) E 547 % 100 = 47 (ARMAZENE ESTA VALOR)
; 47 / 10 = 4 (PRINTAR ESSE 4) E 47 % 10 = 7 (ARMAZENE ESTA VALOR)
; POR FIM BASTA PRINTAR O 7!


END MAIN